export const TOOL_NAME = 'filament-workbench';
export const SUPPORTED_MINECRAFT_VERSION = '1.21.1';
export const SUPPORTED_MOD_LOADER = 'Fabric';
export const SUPPORTED_FILAMENT_VERSION = '1.3.22';

export const JSON_EXT = '.json';

export const VANILLA_ITEMS = new Set<string>([
  'minecraft:air',
  'minecraft:stone',
  'minecraft:sea_lantern',
  'minecraft:paper',
  'minecraft:potion',
  'minecraft:iron_axe',
  'minecraft:iron_hoe',
  'minecraft:iron_pickaxe',
  'minecraft:iron_shovel',
  'minecraft:iron_sword',
  'minecraft:diamond_axe',
  'minecraft:diamond_hoe',
  'minecraft:diamond_pickaxe',
  'minecraft:diamond_shovel',
  'minecraft:diamond_sword',
  'minecraft:netherite_sword',
  'minecraft:bow',
  'minecraft:crossbow',
  'minecraft:fishing_rod',
  'minecraft:leather_helmet',
  'minecraft:leather_chestplate',
  'minecraft:leather_leggings',
  'minecraft:leather_boots',
  'minecraft:chainmail_helmet',
  'minecraft:chainmail_chestplate',
  'minecraft:chainmail_leggings',
  'minecraft:chainmail_boots',
  'minecraft:iron_helmet',
  'minecraft:iron_chestplate',
  'minecraft:iron_leggings',
  'minecraft:iron_boots',
  'minecraft:diamond_helmet',
  'minecraft:diamond_chestplate',
  'minecraft:diamond_leggings',
  'minecraft:diamond_boots',
  'minecraft:netherite_helmet',
  'minecraft:netherite_chestplate',
  'minecraft:netherite_leggings',
  'minecraft:netherite_boots',
  'minecraft:chest',
  'minecraft:barrel',
  'minecraft:shield',
  'minecraft:golden_helmet',
  'minecraft:golden_chestplate',
  'minecraft:golden_leggings',
  'minecraft:golden_boots',
  'minecraft:carved_pumpkin',
  'minecraft:stick',
]);

export const VANILLA_BLOCKS = new Set<string>([
  'minecraft:stone',
  'minecraft:oak_planks',
  'minecraft:spruce_planks',
  'minecraft:chest',
  'minecraft:barrel',
  'minecraft:iron_block',
  'minecraft:gold_block',
]);

export const SAFE_ITEM_BACKINGS = new Set<string>([
  'minecraft:iron_axe',
  'minecraft:iron_hoe',
  'minecraft:iron_pickaxe',
  'minecraft:iron_shovel',
  'minecraft:iron_sword',
  'minecraft:diamond_axe',
  'minecraft:diamond_hoe',
  'minecraft:diamond_pickaxe',
  'minecraft:diamond_shovel',
  'minecraft:diamond_sword',
  'minecraft:netherite_sword',
  'minecraft:bow',
  'minecraft:crossbow',
  'minecraft:fishing_rod',
  'minecraft:paper',
  'minecraft:potion',
  'minecraft:shield',
  'minecraft:sea_lantern',
  'minecraft:leather_helmet',
  'minecraft:leather_chestplate',
  'minecraft:leather_leggings',
  'minecraft:leather_boots',
  'minecraft:chainmail_helmet',
  'minecraft:chainmail_chestplate',
  'minecraft:chainmail_leggings',
  'minecraft:chainmail_boots',
  'minecraft:iron_helmet',
  'minecraft:iron_chestplate',
  'minecraft:iron_leggings',
  'minecraft:iron_boots',
  'minecraft:diamond_helmet',
  'minecraft:diamond_chestplate',
  'minecraft:diamond_leggings',
  'minecraft:diamond_boots',
  'minecraft:netherite_helmet',
  'minecraft:netherite_chestplate',
  'minecraft:netherite_leggings',
  'minecraft:netherite_boots',
  'minecraft:golden_helmet',
  'minecraft:golden_chestplate',
  'minecraft:golden_leggings',
  'minecraft:golden_boots',
  'minecraft:carved_pumpkin',
  'minecraft:stick',
]);

export const SAFE_ARMOR_BACKINGS = new Set<string>([
  'minecraft:leather_helmet',
  'minecraft:leather_chestplate',
  'minecraft:leather_leggings',
  'minecraft:leather_boots',
  'minecraft:chainmail_helmet',
  'minecraft:chainmail_chestplate',
  'minecraft:chainmail_leggings',
  'minecraft:chainmail_boots',
  'minecraft:iron_helmet',
  'minecraft:iron_chestplate',
  'minecraft:iron_leggings',
  'minecraft:iron_boots',
  'minecraft:diamond_helmet',
  'minecraft:diamond_chestplate',
  'minecraft:diamond_leggings',
  'minecraft:diamond_boots',
  'minecraft:netherite_helmet',
  'minecraft:netherite_chestplate',
  'minecraft:netherite_leggings',
  'minecraft:netherite_boots',
  'minecraft:golden_helmet',
  'minecraft:golden_chestplate',
  'minecraft:golden_leggings',
  'minecraft:golden_boots',
  'minecraft:carved_pumpkin',
]);

export const SAFE_BLOCK_BACKINGS = new Set<string>([
  'minecraft:stone',
  'minecraft:oak_planks',
  'minecraft:spruce_planks',
  'minecraft:chest',
  'minecraft:barrel',
  'minecraft:iron_block',
  'minecraft:gold_block',
]);
